WIM_MVC/Controllers/ReportController.cs
using CrystalDecisions.CrystalReports.Engine;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WIM_MVC.CustomFilters;
using WIM_MVC.Models;
using WIM_MVC.Models.EntityFramework;

namespace WIM_MVC.Controllers
{
    public class ReportController : Controller
    {
        private WIMEntities db = new WIMEntities();

        [HttpGet]
        [AuthLog(Roles = "V_Report")]
        public ActionResult Index()
        {
            if (!BaseModel.TestConnection())
            {
                return View("DbConnectionFailed");
            }
            List<LS_Report> model = db.LS_Report.ToList();
            return View(model);
        }


        [HttpPost]
        [AuthLog(Roles = "V_Report")]
        public ActionResult GeneratePDF(string ReportId, string fromDate, string toDate)
        {
            Stream stream = null;
            FileStreamResult pdfFile = null;
            DateTime from = StringToDateTime(fromDate);
            DateTime to = StringToDateTime(toDate);
            if (ReportId == "1")
            {
                ReportDocument rd = new ReportDocument();
                rd.Load(Path.Combine(Server.MapPath("~/Reports/rpt_Report_1.rpt")));
                //rd.SetParameterValue("DonVi", "ABCD");
                //rd.SetParameterValue("TenTram", "TRẠM CÂN QL 20");
                //rd.SetParameterValue("NgayThangNam", "Tháng 01/2016");
                //DateTime fromdate = new DateTime(2016, 04, 15);
                //DateTime todate = DateTime.Now;
                List<Report_1_Models> report = ReportModels.Instant.GetReport1(from, to);
                rd.SetDataSource(report);
                rd.SetParameterValue("DonVi", "01");
                rd.SetParameterValue("TenTram", "TRẠM CÂN QL 20");
                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();
                stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                stream.Seek(0, SeekOrigin.Begin);
                pdfFile = File(stream, "application/pdf");
            }
            else if (ReportId == "2")
            {
                ReportDocument rd = new ReportDocument();
                rd.Load(Path.Combine(Server.MapPath("~/Reports/rpt_Report_2.rpt")));
                //rd.SetParameterValue("DonVi", "ABCD");
                //rd.SetParameterValue("TenTram", "TRẠM CÂN QL 20");
                //rd.SetParameterValue("NgayThangNam", "Tháng 01/2016");
                //DateTime fromdate = new DateTime(2016, 04, 15);
                //DateTime todate = DateTime.Now;
                List<Report_2_Models> report = ReportModels.Instant.GetReport2(from, to);
                rd.SetDataSource(report);
                rd.SetParameterValue("DonVi", "01");
                rd.SetParameterValue("TenTram", "TRẠM CÂN QL 20");
                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();
                stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                stream.Seek(0, SeekOrigin.Begin);
                pdfFile = File(stream, "application/pdf");
            }

            return pdfFile;
        }

        /// <summary>
        /// Parse string "DD/MM/YYYY" to DateTime
        /// </summary>
        /// <param name="date"></param>
        /// <returns></returns>
        DateTime StringToDateTime(string date)
        {
            string[] d = date.Split('/');
            int dd = Convert.ToInt32(d[0]);
            int mm = Convert.ToInt32(d[1]);
            int yy = Convert.ToInt32(d[2]);
            return new DateTime(yy, mm, dd);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WIM_MVC/Views/Report/Index.cshtml
@model IEnumerable<WIM_MVC.Models.EntityFramework.LS_Report>

@section head
{
    <link href="~/Content/bootstrap-datetimepicker.css" rel="stylesheet" media="screen" type="text" />
}


@section scripts
{
<script src="~/Scripts/moment.min.js"></script>
<script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript" src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $('#reportTable tr').click(function () {
            $('#reportTable tr').each(function () {
                $(this).removeClass("selected");
            });
            var id = $(this).attr("id");
            $('#selectedReport').val(id);
            $(this).addClass("selected");
        });

        var date = new Date();
        date.setDate(date.getDate() - 1);
        $('#datetimepicker1').datetimepicker({
            defaultDate: date,
            format: 'DD/MM/YYYY'
        });

        $('#datetimepicker2').datetimepicker({
            defaultDate: Date.now(),
            format: 'DD/MM/YYYY'
        });

    });

    function validateForm() {
        var reportId = $('#selectedReport').val();
        if(reportId == "0")
        {
            //alert("Vui lòng chọn báo cáo");
            $('.overlay').show();
            $('.messagebox').show();
            $('#messageContent').html('Vui lòng chọn báo cáo');
            return false;
        }
        return true;
    };

    </script>
}

@{
    ViewBag.Title = "BÁO CÁO THỐNG KÊ";
    var ReportList = ViewBag.ReportList;
}

<h3>@ViewBag.Title</h3>

@using (Html.BeginForm("GeneratePDF", "Report", FormMethod.Post, 
    new {enctype="multipart/form-data", onsubmit="return validateForm();", @class = "form-horizontal", target = "_blank", role = "form" }))
{
    <hr />
    <div class="col-md-4">
        <table class="wimtable" id="reportTable" style="width:300px">
            <tr id="0">
                <th style="text-align:left">Chọn Báo cáo</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr id="@item.ReportID">
                    <td style="text-align:left">
                        @Html.DisplayFor(modelItem => item.ReportName)
                    </td>
                </tr>
            }
        </table>
    </div>
    
    <div class="col-md-4" style="border-left:1px solid gray;margin-left:400px ">
        <input type="hidden" id="selectedReport" name="ReportId" value="0" />

        <div class="form-group" style="padding:0px 10px">
            @Html.Label("Từ ngày")
            <div class='input-group date' id='datetimepicker1' style="width:180px">
                <input type='text' class="form-control" name="fromDate" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>

        <div class="form-group" style="padding:0px 10px">
            @Html.Label("Đến ngày")
            <div class='input-group date' id='datetimepicker2' style="width:180px">
                <input type='text' class="form-control" name="toDate" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>

        <input type="submit" value="Xem báo cáo" class="btn btn-default" />
    </div>
}