WIM_MVC/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WIM_MVC.Models.EntityFramework;
using PagedList;
using WIM_MVC.CustomFilters;
using WIM_MVC.Models;
using System.Web.Routing;
using System.IO;
using System.ComponentModel;
using System.Windows.Forms;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Reflection;

namespace WIM_MVC.Controllers
{
    public class SearchController : Controller
    {
        private int PAGESIZE = 20;
        private WIMEntities db = new WIMEntities();
        static private GridView grid = new GridView();
        // GET: /Search/
        [AuthLog(Roles = "V_Search")]
        public ActionResult Index()
        {
            if (!BaseModel.TestConnection())
            {
                return View("DbConnectionFailed");
            }

            List<SelectListItem> violate = new List<SelectListItem>();
            violate.Add(new SelectListItem { Text = "Tất cả", Value = "ALL", Selected = true });
            violate.Add(new SelectListItem { Text = "Không vi phạm", Value = "NONVIOLATE", Selected = false });
            violate.Add(new SelectListItem { Text = "Vi phạm", Value = "VIOLATE", Selected = false });
            ViewBag.ViolateLevel = violate;

            List<SelectListItem> laneItems = new List<SelectListItem>();
            laneItems.Add(new SelectListItem { Text = "Tất cả", Value = string.Empty, Selected = true });
            var listLane = db.LS_Lane.ToList();
            listLane.ForEach(p =>
            {
                laneItems.Add(new SelectListItem { Text = p.Name, Value = p.LaneCode, Selected = false });
            });
            ViewBag.LaneItems = laneItems;

            List<SelectListItem> axleItems = new List<SelectListItem>();
            axleItems.Add(new SelectListItem { Text = "Tất cả" , Value = "0", Selected = true });
            axleItems.Add(new SelectListItem { Text = "2", Value = "2", Selected = false });
            axleItems.Add(new SelectListItem { Text = "3", Value = "3", Selected = false });
            axleItems.Add(new SelectListItem { Text = "4", Value = "4", Selected = false });
            axleItems.Add(new SelectListItem { Text = "5", Value = "5", Selected = false });
            axleItems.Add(new SelectListItem { Text = "6", Value = "6", Selected = false });
            axleItems.Add(new SelectListItem { Text = "7", Value = "7", Selected = false });
            ViewBag.Axles = axleItems;

            DateTime todate = DateTime.Now;
            DateTime fromdate = todate.AddDays(-1);

            IPagedList<Trans_VehicleInfo> trans = db.Trans_VehicleInfo
                                                        .Where(w => w.WeightEndTime >= fromdate && w.WeightEndTime <= todate)
                                                        .OrderBy(o => o.WeightEndTime)
                                                        .ToList()
                                                        .ToPagedList(1, PAGESIZE);

            return View(trans);
            //return View();
        }

        [HttpPost]
        public PartialViewResult Search(string violateLevel, string laneItems, string fromDate, string toDate, string axles, string plateNumber, int? page)
        {
            if (!BaseModel.TestConnection())
            {
                return PartialView("DbConnectionFailed", null);
            }

            if (toDate.CompareTo(fromDate) == -1)
            {
                ViewBag.ErrorPeriodTime = true;
            }

            if (fromDate == "" || toDate == "")
            {
                ViewBag.ErrorGetdate = true;
                fromDate = "01/01/0001 12:00:00 SA";
                toDate = "01/01/0001 12:00:00 SA";
            }

            DateTime fromDateParam = DateTime.Parse(fromDate);
            DateTime toDateParam = DateTime.Parse(toDate);
            int axlesCount = string.IsNullOrEmpty(axles) ? -1 : int.Parse(axles);

            ViewBag.ViolateLevel = violateLevel;
            ViewBag.LaneItems = laneItems;
            ViewBag.FromDate = fromDate;
            ViewBag.ToDate = toDate;
            ViewBag.Axles = axles;
            ViewBag.PlateNumber = plateNumber;

            List<Trans_VehicleInfo> temp = db.Trans_VehicleInfo
                .Where(p =>
                    (violateLevel.Equals("ALL")
                        || violateLevel.Equals("NONVIOLATE") && (p.OverloadStatus == 0 || p.OverloadStatus == null)
                        || violateLevel.Equals("VIOLATE") && p.OverloadStatus == 1)
                    && (p.LaneCode.Equals(laneItems) || string.IsNullOrEmpty(laneItems))
                    && p.WeightEndTime >= fromDateParam
                    && p.WeightEndTime <= toDateParam
                    && (p.AxlesCount == axlesCount || axlesCount == 0)
                    && (p.LicensePlate.Contains(plateNumber) || string.IsNullOrEmpty(plateNumber)))
                .OrderBy(p => p.WeightEndTime)
                .ToList();
            IPagedList<Trans_VehicleInfo> trans = temp.ToPagedList(page ?? 1, PAGESIZE);
            ViewBag.TotalSearch = temp.Count;

            grid.DataSource = temp;
            grid.DataBind();
            string sId = string.Empty;
            trans.ToList().ForEach(t =>
            {
                sId = sId + "*" + t.TranId.ToString();
            });
            ViewBag.SID = sId;           

            return PartialView("_TransactionTable",trans);
        }

        public ActionResult ConnectionFailed()
        {
            return View("DbConnectionFailed");
        }

        // GET: /Search/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trans_VehicleInfo trans_vehicleinfo = db.Trans_VehicleInfo.Find(id);
            if (trans_vehicleinfo == null)
            {
                return HttpNotFound();
            }
            return View(trans_vehicleinfo);
        }

        // GET: /Search/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Search/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="VehicleID,ID,MetrologicalID,Version,StartTime,StartTimeStr,LaneNo,ErrorFlag,WarningFlag,ViolationFlag,Direction,MoveStatus,FrontToFront,BackToFront,Duration,VehicleLength,GrossWeight,LeftWeight,RightWeight,Velocity,WheelBase,AxlesCount,MassUnit,VelocityUnit,DistanceUnit,licensePlate,UrlImagelicensePlate,UrlLaneImage,ANPRTime,Status,OverloadPercent,Datalogger_ID,TransactionId,VehicleType,LaneID,FusionWarning")] Trans_VehicleInfo trans_vehicleinfo)
        {
            if (ModelState.IsValid)
            {
                db.Trans_VehicleInfo.Add(trans_vehicleinfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(trans_vehicleinfo);
        }

        // GET: /Search/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trans_VehicleInfo trans_vehicleinfo = db.Trans_VehicleInfo.Find(id);
            if (trans_vehicleinfo == null)
            {
                return HttpNotFound();
            }
            return View(trans_vehicleinfo);
        }

        // POST: /Search/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="VehicleID,ID,MetrologicalID,Version,StartTime,StartTimeStr,LaneNo,ErrorFlag,WarningFlag,ViolationFlag,Direction,MoveStatus,FrontToFront,BackToFront,Duration,VehicleLength,GrossWeight,LeftWeight,RightWeight,Velocity,WheelBase,AxlesCount,MassUnit,VelocityUnit,DistanceUnit,licensePlate,UrlImagelicensePlate,UrlLaneImage,ANPRTime,Status,OverloadPercent,Datalogger_ID,TransactionId,VehicleType,LaneID,FusionWarning")] Trans_VehicleInfo trans_vehicleinfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trans_vehicleinfo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(trans_vehicleinfo);
        }

        // GET: /Search/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trans_VehicleInfo trans_vehicleinfo = db.Trans_VehicleInfo.Find(id);
            if (trans_vehicleinfo == null)
            {
                return HttpNotFound();
            }
            return View(trans_vehicleinfo);
        }

        // POST: /Search/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Trans_VehicleInfo trans_vehicleinfo = db.Trans_VehicleInfo.Find(id);
            db.Trans_VehicleInfo.Remove(trans_vehicleinfo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public void ExportExcel()
        {
            Response.Clear();
            Response.Buffer = true;

WIM_MVC/Views/Search/Create.cshtml
@model WIM_MVC.Models.EntityFramework.Trans_VehicleInfo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Trans_VehicleInfo</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.ID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID)
                @Html.ValidationMessageFor(model => model.ID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MetrologicalID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MetrologicalID)
                @Html.ValidationMessageFor(model => model.MetrologicalID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Version, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Version)
                @Html.ValidationMessageFor(model => model.Version)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime)
                @Html.ValidationMessageFor(model => model.StartTime)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTimeStr, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTimeStr)
                @Html.ValidationMessageFor(model => model.StartTimeStr)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LaneNo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LaneNo)
                @Html.ValidationMessageFor(model => model.LaneNo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ErrorFlag, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ErrorFlag)
                @Html.ValidationMessageFor(model => model.ErrorFlag)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WarningFlag, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WarningFlag)
                @Html.ValidationMessageFor(model => model.WarningFlag)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ViolationFlag, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ViolationFlag)
                @Html.ValidationMessageFor(model => model.ViolationFlag)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direction, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direction)
                @Html.ValidationMessageFor(model => model.Direction)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoveStatus, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoveStatus)
                @Html.ValidationMessageFor(model => model.MoveStatus)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FrontToFront, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FrontToFront)
                @Html.ValidationMessageFor(model => model.FrontToFront)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BackToFront, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BackToFront)
                @Html.ValidationMessageFor(model => model.BackToFront)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration)
                @Html.ValidationMessageFor(model => model.Duration)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleLength, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleLength)
                @Html.ValidationMessageFor(model => model.VehicleLength)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GrossWeight, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GrossWeight)
                @Html.ValidationMessageFor(model => model.GrossWeight)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LeftWeight, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LeftWeight)
                @Html.ValidationMessageFor(model => model.LeftWeight)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RightWeight, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RightWeight)
                @Html.ValidationMessageFor(model => model.RightWeight)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Velocity, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Velocity)
                @Html.ValidationMessageFor(model => model.Velocity)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WheelBase, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WheelBase)
                @Html.ValidationMessageFor(model => model.WheelBase)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AxlesCount, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AxlesCount)
                @Html.ValidationMessageFor(model => model.AxlesCount)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MassUnit, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MassUnit)
                @Html.ValidationMessageFor(model => model.MassUnit)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VelocityUnit, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VelocityUnit)
                @Html.ValidationMessageFor(model => model.VelocityUnit)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DistanceUnit, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DistanceUnit)
                @Html.ValidationMessageFor(model => model.DistanceUnit)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.licensePlate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.licensePlate)
                @Html.ValidationMessageFor(model => model.licensePlate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrlImagelicensePlate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrlImagelicensePlate)
                @Html.ValidationMessageFor(model => model.UrlImagelicensePlate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrlLaneImage, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrlLaneImage)
                @Html.ValidationMessageFor(model => model.UrlLaneImage)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ANPRTime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ANPRTime)
                @Html.ValidationMessageFor(model => model.ANPRTime)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status)
                @Html.ValidationMessageFor(model => model.Status)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OverloadPercent, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OverloadPercent)
                @Html.ValidationMessageFor(model => model.OverloadPercent)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Datalogger_ID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Datalogger_ID)
                @Html.ValidationMessageFor(model => model.Datalogger_ID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransactionId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransactionId)
                @Html.ValidationMessageFor(model => model.TransactionId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleType, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleType)
                @Html.ValidationMessageFor(model => model.VehicleType)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LaneID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LaneID)
                @Html.ValidationMessageFor(model => model.LaneID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FusionWarning, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FusionWarning)
                @Html.ValidationMessageFor(model => model.FusionWarning)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WIM_MVC/Views/Search/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<WIM_MVC.Models.EntityFramework.Trans_VehicleInfo>

@section scripts
{
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script>
        var date = new Date();
        date.setDate(date.getDate() - 1);
        $(function () {
            $('#datetimepicker1').datetimepicker({
                defaultDate: date,
                format: 'DD/MM/YYYY HH:mm:ss'

            });
        });
    </script>
    <script>
        $(function () {
            $('#datetimepicker2').datetimepicker({
                defaultDate: Date.now(),
                format: 'DD/MM/YYYY HH:mm:ss'
            });
        });
        var submittime = Date.now();
        function ajaxfail(objXHR, status, errorThrown)
        {
            var timeout = Date.now() - submittime;
                if (submitcount <= 30000)
                {
                    $("#searchform").submit();
                }
                else
                {
                    submittime = now();
                    $('.overlay').hide();
                    $('.waiting').hide();
                    window.location.href = "@Url.Action("ConnectionFailed", "Search")";
                }
        }
        function ajaxsuccess()
        {
            $('.overlay').hide();
            $('.waiting').hide();
            submitcount = 0;
            addrowheader();
        }
        function btnsearchclick() {
                $('.overlay').show();
                $('.waiting').show();
                timeout = 0;
            };
        
    </script>

    <script type="text/javascript" src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
}




@{
    ViewBag.Title = "TRA CỨU";
}
<h3>@ViewBag.Title</h3>
@using (Ajax.BeginForm("Search", "Search", new AjaxOptions
                                                {
                                                    HttpMethod = "Post",
                                                    UpdateTargetId = "divTransaction",
                                                    OnSuccess = "ajaxsuccess",
                                                    OnFailure = "ajaxfail"
                                                }
                                          , new { id = "searchform"}))
{
    <div>
        <table style="margin-right:auto;margin-left:auto">
            <tr>
                <th style="font-size:12px">Mức độ vi phạm:</th>
                <th style="font-size:12px">Làn số:</th>
                <th style="font-size:12px">Từ ngày:</th>
                <th style="font-size:12px">Đến ngày:</th>
                <th style="font-size:12px">Số trục</th>
                <th style="font-size:12px">Số xe</th>
                <th></th>
            </tr>
            <tr>
                <td width="10%" style="font-size:12px;vertical-align:top">
                    @Html.DropDownList("ViolateLevel", null, new { style = "height:34px" })
                </td>
                <td width="8%" style="font-size:12px;vertical-align:top">   
                    @Html.DropDownList("LaneItems", null, new { style = "height:34px" })
                </td>
                <td width="24%" style="font-size:12px">
                    <!-- Examples of creating a Datepicker -->
                    @*<div class="container">
                        <div class="col-md-10">
                            <div class='well'>*@
                                        <div class="form-group">
                                            <div class='input-group date' id='datetimepicker1'>
                                                <input type='text' class="form-control" name="fromDate" />
                                                <span class="input-group-addon">
                                                    <span class="glyphicon glyphicon-calendar"></span>
                                                </span>
                                            </div>
                                        </div>
                                        @*</div>
                            </div>
                        </div>*@
                </td>
                <td width="24%">
                    <!-- Examples of creating a Datepicker -->
                    @*<div class="container">
                        <div class="col-md-10">
                            <div class='well'>*@
                                        <div class="form-group">
                                            <div class='input-group date' id='datetimepicker2'>
                                                <input type='text' class="form-control" name="toDate"/>
                                                <span class="input-group-addon">
                                                    <span class="glyphicon glyphicon-calendar"></span>
                                                </span>
                                            </div>
                                        </div>
                                @*</div>
                            </div>
                        </div>*@
                </td>
                <td width="10%" style="font-size:12px;vertical-align:top">
                    @Html.DropDownList("Axles", null, new { style = "height:34px" })
                </td>
                <td width="14%" style="font-size:12px;vertical-align:top">
                    <input style="height:34px" type="text" name="plateNumber"/>
                </td>
                <td width="10%" style="font-size:12px;vertical-align:top" align="center">
                    <input style="height:34px" onclick="btnsearchclick()" id="btnSearch" type="submit" value="Lọc" class="btn btn-default" />
                </td>
            </tr>
        </table>
    </div>
}


<div class="tableheader" id="divTransaction" style="margin-bottom:10%">
    @{Html.RenderPartial("_TransactionTable", Model);}
</div>